services:

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: luggage_user
      POSTGRES_PASSWORD: luggage_pass
      POSTGRES_DB: luggage_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U luggage_user -d luggage_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://luggage_user:luggage_pass@db:5432/luggage_db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app

volumes:
  pgdata:
